### ISSUE TITLE
run-loop-opstate incorrect receiver_of concept use

### ISSUE THREAD

**Issue by ccotter** [brycelelbach/wg21_p2300_execution#31]
The current draft defines 

```
template<receiver_of R>
    using run-loop-opstate = unspecified; // exposition only
```

Should this be something more like `template <receiver_of<competion_signatures<set_value_t(), set_stopped_t()>> R> ...`?

**Comment by ericniebler** [comment]
Indeed, thanks!

**Comment by ericniebler** [comment]
Fixed
