### ISSUE TITLE
connect-awaitable correctness

### ISSUE THREAD

**Issue by jtsylve** [brycelelbach/wg21_p2300_execution#51]
The current draft defines *connect-awaitable* as follows: 

```c++
operation-state-task connect-awaitable(DS s, DR r) requires receiver_of<DR, Sigs> {
  exception_ptr ep;
  try {
    if constexpr (same_as<V, void>) {
      co_await std::move(s);
      co_await suspend-complete(set_value, std::move(r));
    } else {
      co_await suspend-complete(set_value, std::move(r), co_await std::move(s));
    }
  } catch(...) {
    ep = current_exception();
  }
  co_await suspend-complete(set_error, std::move(r), std::move(ep));
}
```

I am trying to understand whether this is correct.  What is the purpose of the `set_error` condition after the try/catch block if no exception was thrown? 

Wouldn't moving from `r` here twice cause undefined behavior since after the first move the object could be in an undefined state?

**Comment by jtsylve** [comment]
Since *suspect-complete* can not throw and can not resume, I've now convinced myself that the above is correct.  I suppose it's equivalent to the following:

```c++
operation-state-task connect-awaitable(DS s, DR r) requires receiver_of<DR, Sigs> {
  if constexpr (same_as<V, void>) {
    try {
      co_await std::move(s);
    } catch (...) {
      co_await suspend-complete(set_error, std::move(r), currect_exeception());
      unreachable();
    }
    co_await suspend-complete(set_value, std::move(r));
  } else {
    co_await suspend-complete(set_value, std::move(r), co_await std::move(s));
  }
}
```

Could someone else please confirm and close this issue if that's the case?

**Comment by ericniebler** [comment]
It would be equivalent, except you cannot `co_await` in a `catch` block, which is why it is specified the way it is.
